from django.core.management.base import BaseCommand
from django.contrib.auth.models import User
from core.models import SerieATeam, Player, Gameweek
from django.utils import timezone
from datetime import timedelta
import random


TEAMS = [
    ("Juventus", "JUV", "#000000"),
    ("Inter Milan", "INT", "#0033CC"),
    ("AC Milan", "MIL", "#CC0000"),
    ("Napoli", "NAP", "#00CCFF"),
    ("AS Roma", "ROM", "#8B0000"),
    ("Lazio", "LAZ", "#87CEEB"),
    ("Atalanta", "ATA", "#0000CD"),
    ("Fiorentina", "FIO", "#6A0DAD"),
    ("Torino", "TOR", "#8B4513"),
    ("Bologna", "BOL", "#CC0000"),
    ("Udinese", "UDI", "#000000"),
    ("Sassuolo", "SAS", "#006400"),
    ("Hellas Verona", "VER", "#FFD700"),
    ("Genoa", "GEN", "#8B0000"),
    ("Cagliari", "CAG", "#CC0000"),
    ("Lecce", "LEC", "#FFD700"),
    ("Como", "COM", "#003DA5"),
    ("Parma", "PAR", "#FFCC00"),
    ("Pisa", "PIS", "#000000"),
    ("Cremonese", "CRE", "#CC0000"),
]

PLAYERS = {
    "JUV": [
        ("Michele Di Gregorio", "GK", 5.5),
        ("Mattia Perin", "GK", 4.0),
        ("Bremer", "DEF", 6.0),
        ("Federico Gatti", "DEF", 5.0),
        ("Kalulu", "DEF", 6.0),
        ("Andrea Cambiaso", "DEF", 6.0),
        ("Loyd Kelly", "DEF", 5.0),
        ("Gleison Bremer", "DEF", 6.0),
        ("Manuel Locatelli", "MID", 6.0),
        ("Weston McKennie", "MID", 5.0),
        ("Fabio Miretti", "MID", 5.5),
        ("Kenan Yildiz", "MID", 8.0),
        ("Kephren Thuram", "MID", 6.5),
        ("Edon Zhegrova", "MID", 6.5),
        ("Dusan Vlahovic", "FWD", 9.0),
        ("Jonathan David", "FWD", 6.0),
        ("Lois Openda", "FWD", 8.0),
    ],
    "INT": [
        ("Yann Sommer", "GK", 5.5),
        ("Josep Martinez", "GK", 4.5),
        ("Alessandro Bastoni", "DEF", 7.5),
        ("Francesco Acerbi", "DEF", 5.5),
        ("Manuel Akanji", "DEF", 6.0),
        ("Federico Dimarco", "DEF", 8.0),
        ("Matteo Darmian", "DEF", 5.0),
        ("Carlos Augusto", "DEF", 5.0),
        ("Nicolo Barella", "MID", 8.5),
        ("Hakan Calhanoglu", "MID", 8.0),
        ("Henrikh Mkhitaryan", "MID", 6.0),
        ("Davide Frattesi", "MID", 6.5),
        ("Piotr Zielinski", "MID", 5.0),
        ("Lautaro Martinez", "FWD", 11.0),
        ("Marcus Thuram", "FWD", 9.5),
        ("Pio Esposito", "FWD", 7.5),
        ("Ange-Yoan Bonny", "FWD", 5.5),
    ],
    "MIL": [
        ("Mike Maignan", "GK", 5.5),
        ("Pietro Terraciano", "GK", 4.0),
        ("Koni De Winter", "DEF", 5.0),
        ("Fikayo Tomori", "DEF", 5.5),
        ("Zacary Athekame", "DEF", 5.0),
        ("Strahinja Pavlovic", "DEF", 7.5),
        ("Matteo Gabbia", "DEF", 5.0),
        ("Davide Bartesaghi", "DEF", 5.5),
        ("Pervis Estupinian", "DEF", 5.5),
        ("Adrien Rabiot", "MID", 6.5),
        ("Alexis Saelemaekers", "MID", 7.0),
        ("Christian Pulisic", "MID", 9.5),
        ("Ruben Loftus-Cheek", "MID", 6.0),
        ("Luka Modric", "MID", 7.5),
        ("Ardon Jashari", "MID", 6.0),
        ("Samuele Ricci", "MID", 5.5),
        ("Yousouff Fofana", "MID", 6.0),
        ("Rafael Leao", "FWD", 10.0),
        ("Santiago Gimenez", "FWD", 7.5),
        ("Niclas Fullkrug", "FWD", 5.5),
        ("Christopher Nkunku", "FWD", 8.5),
    ],
    "NAP": [
        ("Alex Meret", "GK", 5.0),
        ("Vanja Milinkovic-Savic", "GK", 5.5),
        ("Giovanni Di Lorenzo", "DEF", 6.5),
        ("Amir Rrahmani", "DEF", 5.5),
        ("Alessandro Buongiorno", "DEF", 6.0),
        ("Mathias Olivera", "DEF", 5.5),
        ("Leonardo Spinazzola", "DEF", 5.0),
        ("Stanislav Lobotka", "MID", 7.0),
        ("Scott McTominay", "MID", 9.5),
        ("Kevin De Bruyne", "MID", 8.0),
        ("Matteo Politano", "MID", 6.0),
        ("Billy Gilmour", "MID", 5.5),
        ("Romelu Lukaku", "FWD", 8.5),
        ("Rasmus Hojlund", "FWD", 7.0),
        ("Antonio Vergara", "FWD", 6.0),
        ("David Neres", "MID", 7.5),
        ("Alisson Santos", "FWD", 5.5),
    ],
    "ROM": [
        ("Mile Svilar", "GK", 5.0),
        ("Pierluigi Gollini", "GK", 4.0),
        ("Gianluca Mancini", "DEF", 5.0),
        ("Evan Ndicka", "DEF", 6.0),
        ("Zeki Celik", "DEF", 5.0),
        ("Angelino", "DEF", 5.5),
        ("Mario Hermoso", "DEF", 5.0),
        ("Lorenzo Pellegrini", "MID", 7.0),
        ("Bryan Cristante", "MID", 5.5),
        ("Wesley", "DEF", 6.5),
        ("Stephan El Shaarawy", "MID", 6.0),
        ("Manu Kone", "MID", 7.0),
        ("Paulo Dybala", "FWD", 9.0),
        ("Artem Dovbyk", "FWD", 6.5),
        ("Evan Ferguson", "FWD", 5.5),
        ("Matias Soulé", "MID", 6.5),
        ("Donyell Malen", "FWD", 8.5),

    ],
    "LAZ": [
        ("Ivan Provedel", "GK", 5.0),
        ("Christos Mandas", "GK", 4.5),
        ("Alessio Romagnoli", "DEF", 5.5),
        ("Patric", "DEF", 4.5),
        ("Adam Marusic", "DEF", 5.0),
        ("Luca Pellegrini", "DEF", 5.0),
        ("Mario Gila", "DEF", 5.0),
        ("Mattia Zaccagni", "MID", 7.5),
        ("Nicolo Rovella", "MID", 6.0),
        ("Kenneth Taylor", "MID", 6.0),
        ("Gustav Isaksen", "MID", 5.5),
        ("Pedro", "MID", 6.0),
        ("Daniel Maldini", "FWD", 7.0),
        ("Tijjani Noslin", "FWD", 6.5),
        ("Loum Tchaouna", "MID", 5.0),
        ("Danilo Cataldi", "MID", 5.5),
        ("Boulaye Dia", "FWD", 7.0),
    ],
    "ATA": [
        ("Marco Carnesecchi", "GK", 5.0),
        ("Juan Musso", "GK", 4.5),
        ("Rafael Toloi", "DEF", 4.5),
        ("Berat Djimsiti", "DEF", 5.0),
        ("Davide Zappacosta", "DEF", 5.5),
        ("Matteo Ruggeri", "DEF", 5.0),
        ("Isak Hien", "DEF", 5.5),
        ("Marten de Roon", "MID", 6.0),
        ("Ederson", "MID", 8.0),
        ("Nicola Zalewski", "MID", 6.5),
        ("Charles De Ketelaere", "MID", 7.0),
        ("Yunus Musah", "MID", 5.5),
        ("Mario Pasalic", "MID", 6.0),
        ("Gianluca Scamacca", "FWD", 8.0),
        ("Nikola Krstovic", "FWD", 6.5),
        ("Lazar Samardzic", "MID", 6.5),
        ("Giacomo Raspadori", "MID", 6.0),
    ],
    "FIO": [
        ("David De Gea", "GK", 5.5),
        ("Oliver Christensen", "GK", 4.0),
        ("Nikola Milenkovic", "DEF", 5.5),
        ("Lucas Martinez Quarta", "DEF", 5.0),
        ("Cristiano Biraghi", "DEF", 5.5),
        ("Michael Kayode", "DEF", 5.0),
        ("Dodô", "DEF", 5.5),
        ("Rolando Mandragora", "MID", 5.5),
        ("Giacomo Bonaventura", "MID", 5.5),
        ("Nicolas Gonzalez", "MID", 7.0),
        ("Jonathan Ikonè", "MID", 6.0),
        ("Albert Gudmundsson", "MID", 7.5),
        ("Moise Kean", "FWD", 9.0),
        ("Lucas Beltran", "FWD", 6.5),
        ("Riccardo Sottil", "FWD", 6.0),
        ("Andrea Colpani", "MID", 6.0),
        ("Robin Gosens", "DEF", 5.5),
    ],
    "TOR": [
        ("Vanja Milinkovic-Savic", "GK", 4.5),
        ("Luca Gemello", "GK", 4.0),
        ("Alessandro Buongiorno", "DEF", 5.5),
        ("Ricardo Rodriguez", "DEF", 5.0),
        ("Mergim Vojvoda", "DEF", 4.5),
        ("Perr Schuurs", "DEF", 5.0),
        ("Ivan Ilic", "MID", 5.5),
        ("Nikola Vlasic", "MID", 6.0),
        ("Valentino Lazaro", "MID", 5.0),
        ("Karol Linetty", "MID", 4.5),
        ("Che Adams", "FWD", 6.0),
        ("Antonio Sanabria", "FWD", 6.0),
        ("Duvan Zapata", "FWD", 7.5),
        ("Nemanja Radonjic", "MID", 5.0),
        ("Alieu Manneh", "FWD", 5.0),
        ("Emirhan Ilkhan", "MID", 4.5),
    ],
    "BOL": [
        ("Lukasz Skorupski", "GK", 4.5),
        ("Federico Ravaglia", "GK", 4.0),
        ("Jhon Lucumi", "DEF", 5.0),
        ("Stefan Posch", "DEF", 5.0),
        ("Sam Beukema", "DEF", 5.5),
        ("Charalampos Lykogiannis", "DEF", 4.5),
        ("Wisdom Amey", "DEF", 4.5),
        ("Lewis Ferguson", "MID", 6.0),
        ("Remo Freuler", "MID", 6.0),
        ("Riccardo Orsolini", "MID", 7.0),
        ("Alexis Saelemaekers", "MID", 6.0),
        ("Michel Aebischer", "MID", 5.0),
        ("Ciro Immobile", "FWD", 7.5),
        ("Federico Bernardeschi", "MID", 6.0),
        ("Joshua Zirkzee", "FWD", 7.0),
        ("Dan Ndoye", "MID", 6.5),
        ("Nicola Moro", "MID", 4.5),
    ],
    "UDI": [
        ("Maduka Okoye", "GK", 4.5),
        ("Simone Obert", "GK", 4.0),
        ("Jaka Bijol", "DEF", 5.0),
        ("Nehuen Perez", "DEF", 4.5),
        ("Destiny Udogie", "DEF", 6.0),
        ("Ebosse", "DEF", 4.5),
        ("Brandon Soppy", "DEF", 4.5),
        ("Sandi Lovric", "MID", 5.0),
        ("Roberto Pereyra", "MID", 5.5),
        ("Lazar Samardzic", "MID", 6.5),
        ("Tolgay Arslan", "MID", 4.5),
        ("Gerard Deulofeu", "MID", 6.0),
        ("Florian Thauvin", "MID", 6.0),
        ("Lorenzo Lucca", "FWD", 7.0),
        ("Alexis Sanchez", "FWD", 6.0),
        ("Isaac Success", "FWD", 5.5),
        ("Martin Payero", "MID", 5.0),
    ],
    "SAS": [
        ("Andrea Consigli", "GK", 4.5),
        ("Stefano Turati", "GK", 4.0),
        ("Gian Marco Ferrari", "DEF", 5.0),
        ("Ruan Tressoldi", "DEF", 4.5),
        ("Rogério", "DEF", 4.5),
        ("Jeremy Toljan", "DEF", 4.5),
        ("Filippo Muldur", "DEF", 4.5),
        ("Maxime Lopez", "MID", 5.5),
        ("Matheus Henrique", "MID", 5.0),
        ("Domenico Berardi", "MID", 8.0),
        ("Nedim Bajrami", "MID", 6.0),
        ("Kristian Thorstvedt", "MID", 5.5),
        ("Andrea Pinamonti", "FWD", 6.5),
        ("Armand Lauriente", "FWD", 6.5),
        ("Luca Moro", "FWD", 6.0),
        ("Janis Antiste", "FWD", 5.5),
        ("Daniel Boloca", "MID", 5.0),
    ],
    "VER": [
        ("Lorenzo Montipo", "GK", 4.5),
        ("Simone Perilli", "GK", 4.0),
        ("Koray Gunter", "DEF", 4.5),
        ("Federico Ceccherini", "DEF", 4.5),
        ("Pawel Dawidowicz", "DEF", 4.5),
        ("Darko Lazovic", "DEF", 5.0),
        ("Filip Uremovic", "DEF", 4.5),
        ("Adrien Tameze", "MID", 5.0),
        ("Antonin Barak", "MID", 6.0),
        ("Davide Faraoni", "DEF", 5.0),
        ("Ondrej Duda", "MID", 5.5),
        ("Grigoris Kastanos", "MID", 5.0),
        ("Milan Djuric", "FWD", 6.0),
        ("Thomas Henry", "FWD", 5.5),
        ("Kevin Lasagna", "FWD", 5.5),
        ("Cyril Ngonge", "FWD", 5.5),
        ("Giangiacomo Magnani", "DEF", 4.5),
    ],
    "GEN": [
        ("Josep Martinez", "GK", 4.5),
        ("Nicola Leali", "GK", 4.0),
        ("Radu Dragusin", "DEF", 5.0),
        ("Johan Vasquez", "DEF", 4.5),
        ("Aaron Martin", "DEF", 4.5),
        ("Stefano Sabelli", "DEF", 4.5),
        ("Alessandro De Winter", "DEF", 4.5),
        ("Morten Frendrup", "MID", 5.5),
        ("Milan Badelj", "MID", 5.0),
        ("Albert Gudmundsson", "MID", 7.5),
        ("Ruslan Malinovskyi", "MID", 6.0),
        ("Mateo Retegui", "FWD", 9.0),
        ("Caleb Ekuban", "FWD", 5.5),
        ("Massimo Coda", "FWD", 6.0),
        ("Junior Messias", "MID", 5.5),
        ("Manolo Portanova", "MID", 5.0),
        ("Filippo Melegoni", "MID", 4.5),
    ],
    "CAG": [
        ("Boris Radunovic", "GK", 4.5),
        ("Simone Scuffet", "GK", 4.0),
        ("Yerry Mina", "DEF", 5.0),
        ("Zito Luvumbo", "MID", 5.5),
        ("Nahitan Nandez", "DEF", 5.0),
        ("Adam Obert", "DEF", 4.5),
        ("Paulo Azzi", "DEF", 4.5),
        ("Alessandro Deiola", "MID", 4.5),
        ("Nicolas Viola", "MID", 5.0),
        ("Razvan Marin", "MID", 5.5),
        ("Gaston Pereiro", "MID", 5.0),
        ("Matteo Prati", "MID", 4.5),
        ("Roberto Piccoli", "FWD", 6.5),
        ("Gianluca Lapadula", "FWD", 6.0),
        ("Leonardo Pavoletti", "FWD", 5.5),
        ("Marko Rog", "MID", 5.0),
        ("Luvumbo", "MID", 5.5),
    ],
    "LEC": [
        ("Wladimiro Falcone", "GK", 4.5),
        ("Blazej Augustyniak", "GK", 4.0),
        ("Frederic Baschirotto", "DEF", 5.0),
        ("Marin Pongracic", "DEF", 5.0),
        ("Antonino Gallo", "DEF", 4.5),
        ("Valentin Gendrey", "DEF", 4.5),
        ("Samuel Umtiti", "DEF", 4.5),
        ("Morten Hjulmand", "MID", 5.5),
        ("Joan Gonzalez", "MID", 5.0),
        ("Pontus Almqvist", "MID", 5.5),
        ("Gabriel Strefezza", "MID", 6.0),
        ("Patrick Dorgu", "DEF", 5.5),
        ("Nikola Krstovic", "FWD", 6.5),
        ("Roberto Piccoli", "FWD", 6.0),
        ("Assan Ceesay", "FWD", 5.5),
        ("Lameck Banda", "MID", 5.0),
        ("Ylber Ramadani", "MID", 5.0),
    ],
    "COM": [
        ("Pepe Reina", "GK", 4.5),
        ("Emil Audero", "GK", 4.5),
        ("Raphael Guerreiro", "DEF", 6.0),
        ("Caleb Okoli", "DEF", 5.0),
        ("Yan Couto", "DEF", 5.5),
        ("Edoardo Goldaniga", "DEF", 4.5),
        ("Alberto Moreno", "DEF", 4.5),
        ("Cesc Fabregas", "MID", 5.0),
        ("Patrick Cutrone", "FWD", 6.0),
        ("Assane Diao", "FWD", 7.0),
        ("Alvaro Morata", "FWD", 8.0),
        ("Maximo Perrone", "MID", 5.5),
        ("Nico Paz", "MID", 7.5),
        ("Gabriel Strefezza", "MID", 6.0),
        ("Albian Hajdari", "DEF", 4.5),
        ("Reda Belahyane", "MID", 5.5),
    ],
    "PAR": [
        ("Zion Suzuki", "GK", 4.5),
        ("Adrian Semper", "GK", 4.0),
        ("Lautaro Valenti", "DEF", 4.5),
        ("Woyo Coulibaly", "DEF", 4.5),
        ("Enrico Del Prato", "DEF", 4.5),
        ("Pontus Almqvist", "DEF", 5.0),
        ("Botond Balogh", "DEF", 4.5),
        ("Adrian Benedyczak", "MID", 5.0),
        ("Ange-Yoan Bonny", "FWD", 6.0),
        ("Dennis Man", "MID", 6.0),
        ("Valentin Mihailă", "MID", 5.5),
        ("Benjamin Cremaschi", "MID", 5.5),
        ("Emanuele Valeri", "DEF", 4.5),
        ("Matteo Cancellieri", "FWD", 5.5),
        ("Enrico Delprato", "DEF", 4.5),
        ("Simon Sohm", "MID", 5.5),
        ("Jayden Braaf", "FWD", 5.5),
    ],
    "PIS": [
        ("Elliot Normal", "GK", 4.5),
        ("Nicolas Andrade", "GK", 4.0),
        ("Alessandro Caracciolo", "DEF", 4.5),
        ("Idrissa Toure", "DEF", 4.5),
        ("Gabriel Charpentier", "FWD", 6.5),
        ("Arena", "DEF", 4.5),
        ("Matteo Tramoni", "MID", 6.0),
        ("Filippo Melegoni", "MID", 5.0),
        ("Samuele Birindelli", "DEF", 4.5),
        ("Stefano Moreo", "FWD", 5.5),
        ("Yann Karamoh", "MID", 5.5),
        ("Nicholas Bonfanti", "FWD", 6.0),
        ("Simone Canestrelli", "DEF", 4.5),
        ("Luca Mazzitelli", "MID", 4.5),
        ("Massimo Piccinini", "MID", 4.5),
        ("George Puscas", "FWD", 5.5),
        ("Tomas Esteves", "DEF", 4.5),
    ],
    "CRE": [
        ("Christophe Ravanel", "GK", 4.5),
        ("Marco Sarr", "GK", 4.0),
        ("Luka Lochoshvili", "DEF", 4.5),
        ("Matteo Bianchetti", "DEF", 4.5),
        ("Emanuele Valeri", "DEF", 4.5),
        ("Antonis Zefkilis", "DEF", 4.5),
        ("David Pickel", "MID", 4.5),
        ("Michele Collocolo", "MID", 5.0),
        ("Léo Girotto", "MID", 4.5),
        ("Tommaso Barbieri", "DEF", 4.5),
        ("Manuel De Luca", "FWD", 6.0),
        ("Cyriel Dessers", "FWD", 6.5),
        ("Ante Bilic", "FWD", 5.5),
        ("Luka Lochoshvili", "DEF", 4.5),
        ("Daniel Ciofani", "FWD", 5.5),
        ("Charles Pickel", "MID", 4.5),
        ("Nicolo Fagioli", "MID", 5.5),
    ],
}


class Command(BaseCommand):
    help = 'Seeds the database with 2025/26 Serie A teams, players and gameweeks'

    def handle(self, *args, **kwargs):
        self.stdout.write('Clearing old data...')
        from core.models import SerieATeam, Player
        Player.objects.all().delete()
        SerieATeam.objects.all().delete()

        self.stdout.write('Seeding 2025/26 teams...')
        team_map = {}
        for name, short, color in TEAMS:
            team, _ = SerieATeam.objects.get_or_create(
                short_name=short,
                defaults={'name': name, 'badge_color': color}
            )
            team_map[short] = team

        self.stdout.write('Seeding players...')
        total = 0
        for short, players in PLAYERS.items():
            team = team_map[short]
            for player_name, position, price in players:
                _, created = Player.objects.get_or_create(
                    name=player_name,
                    team=team,
                    defaults={
                        'position': position,
                        'price': price,
                        'total_points': random.randint(20, 120),
                        'is_available': True,
                    }
                )
                if created:
                    total += 1

        self.stdout.write('Seeding gameweeks...')
        now = timezone.now()
        for i in range(1, 39):
            Gameweek.objects.get_or_create(
                number=i,
                defaults={
                    'name': f'Gameweek {i}',
                    'deadline': now + timedelta(weeks=i - 1),
                    'is_active': i == 1,
                    'is_finished': False,
                }
            )

        self.stdout.write('Creating demo user...')
        if not User.objects.filter(username='demo').exists():
            User.objects.create_user('demo', 'demo@example.com', 'demo1234')

        self.stdout.write(self.style.SUCCESS(
            f'Done! {total} players seeded for 2025/26 Serie A season.'
        ))
    