# Generated by Django 6.0.3 on 2026-03-20 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gameweek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=50)),
                ('deadline', models.DateTimeField()),
                ('is_active', models.BooleanField(default=False)),
                ('is_finished', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='SerieATeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=10)),
                ('badge_color', models.CharField(default='#000000', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('invite_code', models.CharField(max_length=8, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_public', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_leagues', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(choices=[('GK', 'Goalkeeper'), ('DEF', 'Defender'), ('MID', 'Midfielder'), ('FWD', 'Forward')], max_length=3)),
                ('price', models.DecimalField(decimal_places=1, max_digits=4)),
                ('total_points', models.IntegerField(default=0)),
                ('goals_scored', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('clean_sheets', models.IntegerField(default=0)),
                ('yellow_cards', models.IntegerField(default=0)),
                ('red_cards', models.IntegerField(default=0)),
                ('minutes_played', models.IntegerField(default=0)),
                ('is_available', models.BooleanField(default=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='core.serieateam')),
            ],
        ),
        migrations.CreateModel(
            name='Squad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('budget_remaining', models.DecimalField(decimal_places=1, default=100.0, max_digits=5)),
                ('total_points', models.IntegerField(default=0)),
                ('gameweek_points', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='squad', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transferred_at', models.DateTimeField(auto_now_add=True)),
                ('gameweek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.gameweek')),
                ('player_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_in', to='core.player')),
                ('player_out', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_out', to='core.player')),
                ('squad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='core.squad')),
            ],
        ),
        migrations.CreateModel(
            name='GameweekScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('goals', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('clean_sheet', models.BooleanField(default=False)),
                ('yellow_card', models.BooleanField(default=False)),
                ('red_card', models.BooleanField(default=False)),
                ('minutes', models.IntegerField(default=0)),
                ('bonus', models.IntegerField(default=0)),
                ('gameweek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='core.gameweek')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gameweek_scores', to='core.player')),
            ],
            options={
                'unique_together': {('player', 'gameweek')},
            },
        ),
        migrations.CreateModel(
            name='LeagueMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.league')),
                ('squad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='league_memberships', to='core.squad')),
            ],
            options={
                'unique_together': {('league', 'squad')},
            },
        ),
        migrations.CreateModel(
            name='SquadPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_captain', models.BooleanField(default=False)),
                ('is_vice_captain', models.BooleanField(default=False)),
                ('is_on_bench', models.BooleanField(default=False)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.player')),
                ('squad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='squad_players', to='core.squad')),
            ],
            options={
                'unique_together': {('squad', 'player')},
            },
        ),
    ]
